### PR TITLE
add connect page with styles and form

### PR DESCRIPTION
**Pull request by smcalilly**
## Overview
This PR adds the connect page for issue #2. Also includes a working contact form, using the Netlify form backend.

## Notes
- I subscribed the form to the same Zapier webhook that's configured for the Charges app form. Need to make sure this is working correctly.
- I've not coded the images to overlap exactly like the figma design and I'm stuck for the moment. I might need to reassess my CSS approach, or perhaps create the image in a photo editor?
  - It's especially tricky because I didn't find the purple image in the Google Drive, so I had to apply that purple to the image with CSS, via the background-image. This makes it a bit harder to overlap the images, since the child image is contained within the parent div/background image div. Because of this, I'm having trouble making the child image go outside the bounds of the parent div.
- The purple in the figma is different, and darker, than the project's primary color. The figma used the darker purple for links but it blended in with the black text, so I made the links have the primary purple. We can change this however we need.

## Test
See review app: https://deploy-preview-7--thecircuit.netlify.app/connect/

### CODE REVIEW

**Comment by fgregg** [comment]
Looking good:

> I've not coded the images to overlap exactly like the figma design and I'm stuck for the moment. I might need to reassess my CSS approach, or perhaps create the image in a photo editor?

>    It's especially tricky because I didn't find the purple image in the Google Drive, so I had to apply that purple to the image with CSS, via the background-image. This makes it a bit harder to overlap the images, since the child image is contained within the parent div/background image div. Because of this, I'm having trouble making the child image go outside the bounds of the parent div.

I recommend creating the image in a photo editor.

**Comment by smcalilly** [comment]
@fgregg good idea on the photo editing! I've made that change and finished other small things. Now I think I've done everything for this page, let me know if there's anything I'm missing or need to change. Here's a review app: https://deploy-preview-7--thecircuit.netlify.app/connect/

**Comment by fgregg** [comment]
couple of feedback points from me: 

1. the link color should be consistent. including the links to injustice watch and BGA. i.e. the same color
2. i would prefer that the twitter, facebook, and instagram icons be two tone purple and white. (googling for "instagram black and white logo" will give you lots of good options)

**Comment by smcalilly** [comment]
@fgregg I made those color changes. Let me know if that's what you're looking for?

**Comment by fgregg** [comment]
looks great, @smcalilly !

**Comment by fgregg** [comment]
@smcalilly let's rename the connect url to connect_en so if they want to translate to we are already following a good pattern.

After that, we should be good to merge and deploy. I have sign off from Olivia

**Comment by smcalilly** [comment]
@fgregg merged! in the process of deploying

**Pull request merged**
